# Generated by Django 4.0.4 on 2022-06-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tag_id", models.CharField(max_length=255, unique=True)),
                ("tag_text", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("api_key", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("0.1", "Trivial"),
                            ("1.0", "Easy"),
                            ("1.5", "Medium"),
                            ("2", "Hard"),
                        ],
                        default="1.0",
                        max_length=3,
                    ),
                ),
                ("days", models.PositiveIntegerField(default=0)),
                ("delay", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="to_do_overs_app.users"
                    ),
                ),
                ("tags", models.ManyToManyField(to="to_do_overs_app.tags")),
            ],
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="to_do_overs_app.users"
            ),
        ),
    ]
